name: Generate GitHub Tags

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress
      
    - name: Install node dependencies
      run: yarn install --frozen-lockfile --prefer-offline

    - name: Build node dependencies
      run: yarn build
      
    - name: Remove developer folders
      run: |
            rm -r resources/scripts
            rm -r resources/styles
            rm -r node_modules/
            rm -r .parcel-cache/
            
    - name: Remove developer files
      run: |
            rm composer.json package.json composer.lock
            rm README.md .gitignore tsconfig.json
            
    - name: Create a new GitHub developer tag
      run: |
            NEXT_VERSION=$(bash .github/tags/next.sh)

            git config --global user.email "aguiartgv@gmail.com"
            git config --global user.name "Matheus Aguiar(bot)"

            git tag -a v$NEXT_VERSION-dev -m "New developer tag: v$NEXT_VERSION"
            git push origin v$NEXT_VERSION-dev

    - name: Create a new GitHub prod tag
      run: |
            NEXT_VERSION=$(bash .github/tags/next.sh)
            rm -r .github/
            
            git config --global user.email "wpcare@apiki.com"
            git config --global user.name "WP Care"

            git add .
            git commit -am "build: Building a new version"

            git tag -a v$NEXT_VERSION -m "New tag: v$NEXT_VERSION"
            git push origin v$NEXT_VERSION

            echo "All right! 🍕"
